(() => {
'use strict';
const M=window.Mobile6,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let choice=M.config(),project='memorias',members=[{name:'',contribution:''},{name:'',contribution:''},{name:'',contribution:''}],reflections=['','','',''],hints=[0,0,0,0],attempts=[0,0,0,0],results=[],stage=0,dirty=false,app;
const fmt=n=>n.toFixed(1).replace('.',','),today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};$('date').value=today();
const mark=()=>{dirty=true;},status=t=>{$('status').textContent=t;};
function memberUI(){
 $('members').innerHTML=members.map((m,i)=>'<div class="member"><label>Nome do componente '+(i+1)+'<input autocomplete="off" data-member="'+i+'" maxlength="100" value="'+esc(m.name)+'"></label><button type="button" class="secondary" data-remove="'+i+'" aria-label="Remover componente '+(i+1)+'" '+(members.length===1?'disabled':'')+'>Remover</button></div>').join('');$('addMember').disabled=members.length>=8;contributions();
}
function contributions(){
 $('contributions').innerHTML=members.map((m,i)=>'<label data-contrib-label="'+i+'">'+esc(m.name||'Componente '+(i+1))+' · O que você fez?<textarea data-contribution="'+i+'" maxlength="800" placeholder="Descreva sua participação real; não há pontuação automática por este texto.">'+esc(m.contribution)+'</textarea></label>').join('');
}
$('members').addEventListener('input',e=>{if(e.target.dataset.member===undefined)return;const i=Number(e.target.dataset.member);members[i].name=e.target.value;const l=document.querySelector('[data-contrib-label="'+i+'"]');l.firstChild.textContent=(e.target.value||'Componente '+(i+1))+' · O que você fez?';mark();});
$('members').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b||members.length===1)return;const i=Number(b.dataset.remove);if((members[i].name||members[i].contribution)&&!confirm('Remover este componente e sua contribuição?'))return;members.splice(i,1);memberUI();mark();});
$('addMember').onclick=()=>{if(members.length<8){members.push({name:'',contribution:''});memberUI();[...$('members').querySelectorAll('input')].at(-1)?.focus();mark();}};
$('contributions').addEventListener('input',e=>{if(e.target.dataset.contribution!==undefined){members[Number(e.target.dataset.contribution)].contribution=e.target.value;mark();}});
['team','date'].forEach(id=>$(id).addEventListener('input',mark));
function resetLab(){app=new M.App(choice,project);M.draw($('lab'),app);}
$('resetLab').onclick=resetLab;
$('project').onchange=()=>{project=$('project').value;results=[];renderStage();resetLab();scoreUI();mark();status('Projeto alterado. As escolhas de código foram preservadas; confira novamente os testes e as reflexões para esta trilha.');};
function optionLabel(s){return s.replaceAll('PASTA',M.PROJECTS[project].folder);}
function stageNav(){ $('stage-nav').innerHTML=M.GROUPS.map((g,i)=>'<button type="button" data-stage="'+i+'" aria-pressed="'+(stage===i)+'">'+(i+1)+' · '+g.title+'</button>').join(''); }
function renderStage(){const g=M.GROUPS[stage];stageNav();$('stage-meta').textContent='ETAPA '+(stage+1)+' · '+g.minutes+' MINUTOS · ATÉ '+fmt(g.points)+' PONTOS';$('stage-title').textContent=g.title;
 $('config-fields').innerHTML=g.fields.map(([k,label,options])=>'<label>'+label+'<select data-config="'+k+'" id="cfg-'+k+'"><option value="">Escolha um trecho…</option>'+options.map(([v,t])=>'<option value="'+v+'" '+(choice[k]===v?'selected':'')+'>'+esc(optionLabel(t))+'</option>').join('')+'</select><code class="chosen-code" data-chosen="'+k+'">'+esc(optionLabel(options.find(o=>o[0]===choice[k])?.[1]||''))+'</code></label>').join('');
 $('reflection').value=reflections[stage];$('hint').hidden=true;$('hintToggle').setAttribute('aria-expanded','false');$('hint').innerHTML=esc(g.hint)+'<div class="actions"><a class="button secondary" href="../Aula_06_Mobile_Navegacao_Formularios.html#'+g.slide+'" target="aula06" rel="noopener">Rever o slide '+Number(g.slide.slice(1))+'</a></div>';
 $('previousStage').disabled=stage===0;$('nextStage').disabled=stage===M.GROUPS.length-1;testUI();}
function go(i){stage=Math.max(0,Math.min(3,i));renderStage();$('stage-title').scrollIntoView({block:'start',behavior:'auto'});}
$('stage-nav').onclick=e=>{const b=e.target.closest('[data-stage]');if(b)go(Number(b.dataset.stage));};$('previousStage').onclick=()=>go(stage-1);$('nextStage').onclick=()=>go(stage+1);
$('config-fields').onchange=e=>{if(!e.target.dataset.config)return;choice[e.target.dataset.config]=e.target.value;document.querySelector('[data-chosen="'+e.target.dataset.config+'"]').textContent=e.target.value?e.target.selectedOptions[0].textContent:'';results=results.filter(r=>r.group!==stage);testUI();scoreUI();resetLab();mark();};
$('reflection').oninput=()=>{reflections[stage]=$('reflection').value;mark();};
$('hintToggle').onclick=()=>{const open=$('hint').hidden;$('hint').hidden=!open;$('hintToggle').setAttribute('aria-expanded',String(open));if(open){hints[stage]++;mark();}};
function testUI(){const rs=results.filter(x=>x.group===stage);$('tests').innerHTML=rs.length?rs.map(r=>'<div class="testrow '+r.status+'"><strong>'+(r.status==='pass'?'Passou':r.status==='fail'?'Ajustar':'Pendente')+' · '+esc(r.label)+' · '+fmt(r.earned)+' / '+fmt(r.max)+'</strong>'+(r.status==='pass'?'<span class="small">Comportamento verificado na cópia isolada desta etapa.</span>':'<span class="small">'+esc(r.status==='pending'?'Escolha todos os trechos desta etapa para testar.':r.hint)+'</span>')+'</div>').join(''):'<p class="stage-note">Escolha os trechos e use “Conferir esta etapa”. Os testes ainda não foram executados sobre estas escolhas.</p>';}
function scoreUI(){const total=results.reduce((a,r)=>a+r.earned,0);$('score').textContent=fmt(total)+' / 10,0';$('grade-summary').innerHTML='<table class="score-table"><thead><tr><th>Etapa</th><th>Resultado</th></tr></thead><tbody>'+M.GROUPS.map((g,i)=>'<tr><td>'+esc(g.title)+'</td><td>'+fmt(results.filter(r=>r.group===i).reduce((a,r)=>a+r.earned,0))+' / '+fmt(g.points)+'</td></tr>').join('')+'</tbody></table>';}
$('testStage').onclick=()=>{attempts[stage]++;results=[...results.filter(r=>r.group!==stage),...M.evaluate(choice,project,stage)].sort((a,b)=>a.id-b.id);testUI();scoreUI();mark();};
function recheck(){results=M.evaluate(choice,project);testUI();scoreUI();}
function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s&&s>='2000-01-01'&&s<='2100-12-31';}
function identity(){const list=members.filter(m=>m.name.trim());if(!list.length)throw Error('Preencha pelo menos um nome de componente antes de gerar o documento.');if(list.some(m=>m.name.trim().length<2))throw Error('Revise os nomes dos componentes.');const normalized=list.map(m=>m.name.trim().normalize('NFC').toLowerCase());if(new Set(normalized).size!==list.length)throw Error('Há nomes repetidos. Confira os componentes antes de exportar.');if(!validDate($('date').value))throw Error('Informe uma data válida para a atividade.');return list.map(m=>({name:m.name.trim(),contribution:m.contribution.trim()}));}
function snapshot(){return {schema:'mobile-a06-v1',version:M.VERSION,project,team:$('team').value,date:$('date').value,members:members.map(m=>({...m})),choice:{...choice},reflections:[...reflections],hints:[...hints],attempts:[...attempts]};}
function model(){const list=identity();recheck();const date=$('date').value.split('-').reverse().join('/');const total=results.reduce((a,r)=>a+r.earned,0);return {title:'Navegação e formulários',subtitle:'Relatório da oficina interativa',discipline:'Programação para Dispositivos Móveis',lesson:'Aula 06',version:M.VERSION,professor:'Prof. Dr. Thales Levi Azevedo Valente',course:'Técnico em Informática Integrado ao Ensino Médio · 3º ano',team:$('team').value.trim()||'Equipe sem nome',project:M.PROJECTS[project].name,date,members:list.map(m=>m.name),score:fmt(total)+' / 10,0',sections:[
 {title:'1. Controle do documento',items:[['Finalidade','Registrar a configuração construída pela equipe e o resultado dos testes desta oficina de 50 minutos.'],['Versão do material',M.VERSION],['Natureza do resultado','Pontuação automática formativa, sujeita à conferência docente. Não é nota oficial nem comprovante autenticado. Os testes usam um simulador HTML/JavaScript; não verificam um aplicativo Expo executado no celular.'],['Pontuação total',fmt(total)+' de 10,0 pontos. Cada verificação vale 0,5; tentativas e dicas não descontam pontos.']]},
 {title:'2. Pontuação e verificações',items:M.GROUPS.flatMap((g,i)=>[[g.title,fmt(results.filter(r=>r.group===i).reduce((a,r)=>a+r.earned,0))+' / '+fmt(g.points)],...results.filter(r=>r.group===i).map(r=>[r.label,(r.status==='pass'?'Passou':r.status==='fail'?'Ajustar':'Pendente')+' — '+fmt(r.earned)+' / '+fmt(r.max)+(r.status==='fail'?'. '+r.hint:'')])])},
 {title:'3. Escolhas da equipe',items:M.GROUPS.flatMap(g=>g.fields.map(([k,t,opts])=>[t,optionLabel(opts.find(x=>x[0]===choice[k])?.[1]||'Não escolhido').replaceAll('→',' / ')]))},
 {title:'4. Reflexões e uso das dicas',items:M.GROUPS.map((g,i)=>[g.title,(reflections[i].trim()||'Reflexão não registrada.')+'\nConferências solicitadas: '+attempts[i]+'. Aberturas da dica: '+hints[i]+'.'])},
 {title:'5. Participação individual',items:list.map(m=>[m.name,m.contribution||'Participação não descrita. A ser conferida pelo professor.'])},
 {title:'6. Limites e entrega',items:[['O que este documento demonstra','O relatório foi recalculado a partir das escolhas atuais. Os testes de cada etapa isolam aquela habilidade; a prévia do laboratório reúne todas as escolhas. Uma nova tentativa substitui o resultado, sem acumular pontos.'],['O que ainda depende do professor','A compreensão individual, o trabalho no projeto nativo, a autoria e as explicações não recebem nota automática por presença de texto.'],['Privacidade','Nomes e respostas foram processados neste navegador. O documento não foi enviado automaticamente. Entregue pelo meio combinado e não publique esta cópia em repositório público.']]}]};}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function filename(ext){const team=($('team').value||'equipe').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60)||'equipe';return 'mobile_aula06_'+team+'_atividade.'+ext;}
$('pdf').onclick=()=>{try{const m=model();download(new Blob([window.FormalPdf.generate(m)],{type:'application/pdf'}),filename('pdf'));status('PDF gerado com '+m.score+' pontos. Abra e confira o arquivo. Para continuar depois, guarde também a cópia JSON. Nada foi enviado ao professor.');}catch(e){status(e.message);}};
$('json').onclick=()=>{download(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),filename('json'));dirty=false;status('Cópia baixada. Ela contém nomes e respostas: guarde de forma privada. Na reabertura, os testes serão recalculados.');};
$('printReport').onclick=()=>{try{const m=model();const html='<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Relatório Mobile Aula 06</title><style>@page{size:A4;margin:25mm}body{font:12pt/1.5 Georgia,serif;max-width:175mm;margin:25px auto;color:#20362b}h1,h2{color:#006b3c}p{text-align:justify}h2{break-after:avoid;border-left:5px solid #b62932;padding-left:10px}.cover{break-after:page;border-top:9px solid #006b3c;padding-top:25mm}dt{font-weight:bold;margin-top:14px}dd{margin:0;white-space:pre-wrap;text-align:justify}@media print{button{display:none}}</style><body><button onclick="window.print()">Imprimir / Salvar como PDF</button><section class="cover"><p>INSTITUTO FEDERAL DO MARANHÃO · Campus Itapecuru-Mirim</p><h1>'+esc(m.title)+'</h1><h2>'+esc(m.subtitle)+'</h2><p>'+esc(m.course)+'<br>'+esc(m.professor)+'</p><p>Equipe: '+esc(m.team)+'<br>Projeto: '+esc(m.project)+'<br>Data: '+esc(m.date)+'</p><p>Componentes: '+m.members.map(esc).join('; ')+'</p><h2>'+esc(m.score)+' pontos</h2><p>Resultado automático formativo, sujeito à conferência docente.</p></section>'+m.sections.map(s=>'<section><h2>'+esc(s.title)+'</h2><dl>'+s.items.map(([l,v])=>'<dt>'+esc(l)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl></section>').join('')+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),120000);status('Documento para impressão aberto. Escolha Imprimir / Salvar como PDF. Nesta alternativa, o navegador controla margens e paginação.');}catch(e){status(e.message);}};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('O limite desta cópia é 100 KB.');const data=JSON.parse(await file.text());if(data.schema!=='mobile-a06-v1'||!Object.hasOwn(M.PROJECTS,data.project))throw Error('Essa cópia não pertence à atividade da Aula 06 de Mobile.');const text=(v,n)=>{if(typeof v!=='string'||v.length>n)throw Error('Texto inválido ou longo demais na cópia.');return v;};text(data.team,80);if(!validDate(data.date))throw Error('Data inválida na cópia.');if(!Array.isArray(data.members)||data.members.length<1||data.members.length>8)throw Error('A cópia deve conter entre 1 e 8 componentes.');const ms=data.members.map(m=>({name:text(m.name,100),contribution:text(m.contribution||'',800)}));if(!Array.isArray(data.reflections)||data.reflections.length!==4)throw Error('Reflexões inválidas.');const rr=data.reflections.map(x=>text(x,1500));if(!data.choice||typeof data.choice!=='object'||Array.isArray(data.choice))throw Error('Escolhas inválidas.');const cc=M.config(data.choice);const counts=x=>Array.from({length:4},(_,i)=>Number.isSafeInteger(x?.[i])?Math.min(999,Math.max(0,x[i])):0);if(!confirm('Substituir o preenchimento desta aba pela cópia escolhida?'))return;project=data.project;choice=cc;members=ms;reflections=rr;hints=counts(data.hints);attempts=counts(data.attempts);$('team').value=data.team;$('date').value=data.date;$('project').value=project;memberUI();renderStage();resetLab();recheck();dirty=false;status('Cópia reaberta. Testes recalculados sobre os trechos importados; nenhuma pontuação informada pelo arquivo foi aceita.');}catch(err){status('Não foi possível importar: '+err.message);}finally{e.target.value='';}};
let remaining=3000,tick=null;function stop(){clearInterval(tick);tick=null;$('timer').textContent=remaining?'Continuar tempo':'Tempo encerrado';}function clock(){$('clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');}
$('timer').onclick=()=>{if(tick){stop();return;}if(!remaining)return;let last=Date.now();tick=setInterval(()=>{const now=Date.now(),elapsed=Math.floor((now-last)/1000);if(elapsed){remaining=Math.max(0,remaining-elapsed);last+=elapsed*1000;clock();if(!remaining)stop();}},250);$('timer').textContent='Pausar tempo';};$('timerReset').onclick=()=>{stop();remaining=3000;clock();$('timer').textContent='Iniciar tempo';};document.addEventListener('visibilitychange',()=>{if(document.hidden&&tick)stop();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
memberUI();renderStage();resetLab();scoreUI();window.MobileActivity={snapshot,model,recheck,get results(){return results;},get app(){return app;}};
})();