const LESSON_SLIDES=window.LESSON_SLIDES_PARTS||[];
(() => {
'use strict';const $=id=>document.getElementById(id),M=window.Mobile6;let current=0,reading=innerWidth<850;const demos=new Map();
$('deck').innerHTML=LESSON_SLIDES.map((s,i)=>'<section class="slide" id="s'+String(i+1).padStart(2,'0')+'" aria-labelledby="t'+i+'"><div class="meta"><span>MOBILE / AULA 06 / '+s.time+'</span><strong>IFMA · ITAPECURU-MIRIM</strong></div><h1 id="t'+i+'">'+s.title+'</h1><div class="content">'+s.body+'</div><footer><span>Prof. Dr. Thales Levi Azevedo Valente</span><span>'+String(i+1).padStart(2,'0')+' / '+LESSON_SLIDES.length+'</span></footer></section>').join('');
$('index-list').innerHTML=LESSON_SLIDES.map((s,i)=>'<button type="button" data-jump="'+i+'">'+(i+1)+' · '+s.title+'</button>').join('');
const slides=[...document.querySelectorAll('.slide')];
function fit(){const bar=$('toolbar').offsetHeight+8;$('viewport').style.bottom=bar+'px';if(reading)$('deck').style.marginBottom=(bar+20)+'px';else $('deck').style.marginBottom='';const scale=Math.min((innerWidth-12)/1280,(innerHeight-bar-8)/720);document.documentElement.style.setProperty('--scale',String(Math.max(.1,scale)));}
function show(n,update=true){current=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>s.classList.toggle('active',i===current));$('counter').textContent=(current+1)+' / '+slides.length;$('prev').disabled=current===0;$('next').disabled=current===slides.length-1;$('speaker-note').textContent=LESSON_SLIDES[current].note+'\n\nFonte: '+LESSON_SLIDES[current].source;if(update)history.replaceState(null,'','#'+slides[current].id);if(reading&&update)slides[current].scrollIntoView({block:'start'});fit();}
function setReading(v){reading=v;document.body.classList.toggle('reading',v);$('reading').textContent=v?'Modo slides':'Modo leitura';fit();}
function hash(){const m=location.hash.match(/^#s(\d+)$/);show(m?Number(m[1])-1:0,false);if(reading&&m)setTimeout(()=>slides[current].scrollIntoView({block:'start'}),0);}
function resetDemo(){const el=slides[current].querySelector('[data-demo]');if(el){const a=new M.App({...M.GOOD});M.draw(el,a);demos.set(el,a);}if(current===4)$('file-result').textContent='Escolha um arquivo para ver sua função.';if(current===7){stack=['Lista'];$('stack-result').textContent='Lista';}if(current===11){$('state-input').value='';$('state-output').textContent='titulo = \"\"';}if(current===12)$('validation-result').textContent='O formulário deve aceitar qualquer texto? Preveja e clique.';slides[current].querySelectorAll('.answer').forEach(a=>a.hidden=true);slides[current].querySelectorAll('[data-reveal]').forEach(b=>b.setAttribute('aria-expanded','false'));}
document.querySelectorAll('[data-demo]').forEach(el=>{const a=new M.App({...M.GOOD});M.draw(el,a);demos.set(el,a);});
$('prev').onclick=()=>show(current-1);$('next').onclick=()=>show(current+1);$('reading').onclick=()=>setReading(!reading);$('index').onclick=()=>$('index-dialog').showModal();$('notes').onclick=()=>$('notes-dialog').showModal();$('reset').onclick=resetDemo;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('index-list').onclick=e=>{const b=e.target.closest('[data-jump]');if(b){$('index-dialog').close();show(Number(b.dataset.jump));}};
document.querySelectorAll('[data-reveal]').forEach(b=>{b.setAttribute('aria-expanded','false');b.onclick=()=>{const a=b.nextElementSibling;a.hidden=!a.hidden;b.setAttribute('aria-expanded',String(!a.hidden));};});
const files={list:'/memorias · index.tsx é a tela padrão da pasta.',detail:'/memorias/1 ou /memorias/2 · [id].tsx recebe o identificador.',form:'/memorias/nova · nova.tsx é um endereço fixo.',layout:'_layout.tsx não é um endereço de página. Ele organiza o navegador das telas.'};document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>$('file-result').textContent=files[b.dataset.file]);
let stack=['Lista'];document.querySelectorAll('[data-stack]').forEach(b=>b.onclick=()=>{const x=b.dataset.stack;if(x==='push')stack.push('Detalhe');if(x==='replace')stack[stack.length-1]='Formulário';if(x==='back'&&stack.length>1)stack.pop();if(x==='reset')stack=['Lista'];$('stack-result').textContent=stack.join(' → ');});
$('state-input').oninput=e=>$('state-output').textContent='titulo = '+JSON.stringify(e.target.value);
const vals={empty:['',''],spaces:['    ','                  '],short:['ab','curto'],valid:['  Nova memória  ','  Um registro inventado da oficina.  ']};document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [t,r]=vals[b.dataset.check],a=new M.App({...M.GOOD});a.input('titulo',t);a.input('resumo',r);const e=a.validate();$('validation-result').textContent='Título: '+JSON.stringify(t)+'; resumo: '+JSON.stringify(r)+'. '+(Object.keys(e).length?Object.values(e).join(' '):'Passou nas duas regras. Pode seguir para o registro.');});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('input,textarea,select,button,a'))return;if(e.key==='ArrowRight'){e.preventDefault();show(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1);});
window.addEventListener('resize',fit);window.addEventListener('hashchange',hash);setReading(reading);hash();window.MobileLesson={show,setReading,get current(){return current;},slides};
})();